id: AE6CACB9D
title: Prayer for the Tradition of Guru Padmasambhava
type: translation
pechas:
- I5570512B
- IE9705450
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2023-01-04 11:47:10.779328
  last_modified_at: 2023-01-04 11:47:10.779341
  collections:
  - Dudjom Rinpoche Series
  - Works of Tibetan Masters
alignment_to_base:
  I5570512B/6F73: AA0D
  IE9705450/5AA9: AA0D
